server:
  port: 9000
  ssl:
#    certificate: "classpath:any.local.crt"
#    certificate-private-key: "classpath:any.local.key"

    key-store: "classpath:any.local.p12"
    key-store-password: ""
    keyStoreType: PKCS12

    #client-auth: need
#spring.security.user.name=user
#spring.security.user.password=user


#-----------------------------------------------------------------------------
consul:
  enabled: false
  url: "http://localhost:8500"
  acltoken: "1f57b9dc-e104-8843-519b-7f795bc8a364"
  service:
    id: "tokenexchange"
    name: "tokenexchange"
    host: "https://tokenexchange.local"
    port: 443
    delay: 10000
    ttl: 15000
    tags:
      - APIM
      - tokenexchange
      - МС Контекста запроса
    note: "tokenexchange alive and reachable"


vault:
  enabled: true
  host: localhost
  port: 8200
  ssl:
    # store/cert
    type: cert
    #key-store: classpath:localhost.p12
    #key-store-type: PKCS12
    #key-store-password: 1979
    certificate: classpath:localhost.crt
    key: classpath:localhost.key
  paths:
    apim:
      apps:
        config:
          kcusers:
            db-username: spring.datasource.username
            db-password: spring.datasource.password
            service-keycloak-client-secret: service.keycloakclient.client.client-secret
