server:
  port: 9000
  ssl:
    certificate: "classpath:any.local.crt"
    certificate-private-key: "classpath:any.local.key"
#spring.security.user.name=user
#spring.security.user.password=user


#-----------------------------------------------------------------------------
consul:
  enabled: true
  url: "http://localhost:8500"
  acltoken: "1f57b9dc-e104-8843-519b-7f795bc8a364"
  service:
    id: "tokenexchange"
    name: "tokenexchange"
    host: "https://tokenexchange.local"
    port: 443
    delay: 10000
    ttl: 15000
    tags:
      - APIM
      - tokenexchange
      - МС Контекста запроса
    note: "tokenexchange alive and reachable"


